server:
  port: 9000

spring:
  application:
    name: ft-gateway
  cloud:
    gateway:
      actuator:
        verbose: true
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/