server:
  port: 8088
spring:
  application:
    name: service-config
  cloud:
    #Config?????
    config:
      label: master #????
      server:
        git:
          uri: http://10.108.186.154/dalian-alp-group/springcloudtest.git
          username: automan
          password: jiajia1989829*
          search-paths: myconfig

  #rabbitmq???? 15672?Web????????5672?MQ?????
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#?????eureka??
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
      register-with-eureka: true
      #??????????
      fetch-registry: true

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
#eureka.client.service-url.defaultZone = http://localhost:8081/eureka
# ??????

#spring.application.name = service-config
# ??????(git)
#spring.cloud.config.server.git.uri = http://10.108.186.154/dalian-alp-group/springcloudtest.git
#spring.cloud.config.server.git.username = automan
#spring.cloud.config.server.git.password = jiajia1989829*
# ?????
#spring.cloud.config.server.git.search-paths = myconfig
# git???
#spring.cloud.config.label = master
#spring.rabbitmq.host= localhost
#spring.rabbitmq.port= 5672
#spring.rabbitmq.username= guest
#spring.rabbitmq.password= guest
#management.endpoints.web.exposure.include=bus-refresh
#management.endpoint.bus-refresh.enabled=true
#management.endpoint.health.show-details= ALWAYS

