spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tommyma/ft.lab.radae.dev
          username: tommycpma
          password: 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


server:
  port: 9100

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/